### ISSUE TITLE
Línea del tiempo de web

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/actividad-7-EdgarExa#1]
![linea de tiempo_121446](https://user-images.githubusercontent.com/112437707/195632931-00b416ac-547b-4ff9-9db5-4ab7470f4045.jpeg)

Edgar Axel Sandoval Hernández
Línea del tiempo de la web

**Comment by josealfredo79** [comment]
Calificacion 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
